[project]
name = "register-login-system-project"
version = "0.1.0"
description = "A simulation of a login system with custom exceptions, basic encryption and fundamental functionalities."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
